---
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns3
spec: {}
status: {}