---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OM_TARGET:
  OM_CLIENT_ID:
  OM_CLIENT_SECRET:
  OM_SKIP_SSL_VALIDATION:
  PKS_API_ENDPOINT:
  ENV:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:
  CREDHUB_CA_CERT:
  CREDHUB_PREFIX:

inputs:
- name: repository

run:
  path: repository/tasks/create-profiles/task.sh
