resources:
- name: repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

jobs:
- name: create-profiles
  plan:
  - in_parallel:
    - get: repo
  - task: create-profiles
    file: repo/tasks/create-profiles/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_CLIENT_ID: ((om_client_id))
      OM_CLIENT_SECRET: ((om_client_secret))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      ENV: ((env))
    input_mapping:
      repository: repo
