resources:
- name: repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

jobs:
- name: create-profiles
  plan:
  - in_parallel:
    - get: repo
      trigger: true
  - task: create-profiles
    file: repo/tasks/create-profiles/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_CLIENT_ID: ((om_client_id))
      OM_CLIENT_SECRET: ((om_client_secret))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      ENV: ((env))
      CREDHUB_CLIENT: ((credhub.client))
      CREDHUB_SECRET: ((credhub.client_secret))
      CREDHUB_SERVER: ((credhub.server))
      CREDHUB_CA_CERT: ((credhub.ca_cert))
      CREDHUB_PREFIX: ((credhub.prefix))
    input_mapping:
      repository: repo

- name: delete-clusters
  plan:
  - in_parallel:
    - get: repo
      trigger: true
  - task: delete-clusters
    file: repo/tasks/delete-cluster/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_CLIENT_ID: ((om_client_id))
      OM_CLIENT_SECRET: ((om_client_secret))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      ENV: ((env))
    input_mapping:
      repository: repo

- name: create-cluster
  plan:
  - in_parallel:
    - get: repo
      passed: [create-profiles]
      trigger: true
  - task: create-cluster
    file: repo/tasks/create-cluster/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_CLIENT_ID: ((om_client_id))
      OM_CLIENT_SECRET: ((om_client_secret))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      ENV: ((env))
    input_mapping:
      repository: repo

- name: update-cluster
  plan:
  - in_parallel:
    - get: repo
      passed: [create-profiles]
      trigger: true
  - task: update-cluster
    file: repo/tasks/update-cluster/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_CLIENT_ID: ((om_client_id))
      OM_CLIENT_SECRET: ((om_client_secret))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      ENV: ((env))
    input_mapping:
      repository: repo

- name: create-namespaces
  plan:
  - in_parallel:
    - get: repo
      passed: [create-cluster]
      trigger: true
  - task: create-namespaces
    file: repo/tasks/create-namespaces/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_CLIENT_ID: ((om_client_id))
      OM_CLIENT_SECRET: ((om_client_secret))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      ENV: ((env))
    input_mapping:
      repository: repo

- name: delete-namespaces
  plan:
  - in_parallel:
    - get: repo
      passed: [create-namespaces]
      trigger: true
  - task: delete-namespaces
    file: repo/tasks/delete-namespaces/task.yml
    params:
      OM_TARGET: ((om_target))
      OM_CLIENT_ID: ((om_client_id))
      OM_CLIENT_SECRET: ((om_client_secret))
      OM_SKIP_SSL_VALIDATION: ((om_skip_ssl_validation))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      ENV: ((env))
    input_mapping:
      repository: repo